spring:
  cloud:
    gateway:
      routes:
        - id: customer-service-docs
          uri: http://localhost:8081
          predicates:
            - Path=/customers/v3/api-docs
          filters:
            - RewritePath=/customers/v3/api-docs, /v3/api-docs
        - id: account-service-docs
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/v3/api-docs
          filters:
            - RewritePath=/accounts/v3/api-docs, /v3/api-docs
        - id: payment-service-docs
          uri: http://localhost:8083
          predicates:
            - Path=/payments/v3/api-docs
          filters:
            - RewritePath=/payments/v3/api-docs, /v3/api-docs
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**
        - id: account-service
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/payments/**
